create table if not exists global_operating_unit(
operating_unit Integer not null,
operating_unit_description Integer null,
opunit_short_description varchar(255) null,
budgetary_only varchar(255) null,
nature varchar(255) null,
pgc_description varchar(255) null,
file_identifier_position char null,
file_identifier_length varchar(255) null,
branch_identifier_position varchar(255) null,
branch_identifier_length varchar(255) null,
file_national_id_length varchar(255) null,
setid_number_position varchar(255) null,
setid_number_length varchar(255) null,
file_total_length varchar(255) null,
pgc_effective_date varchar(255) null,
pgc_status varchar(255) null,
psgl_status varchar(255) null,
entity_state varchar(255) null,
remarks varchar(255) null,
constraint global_operating_unit_pk primary key(operating_unit));